/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeebox.vistas;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Katherine
 */
public class PestanasPrincipal extends javax.swing.JFrame {
    
    boolean faceRecoder = false;
    boolean activityRender = false;

    /**
     * Creates new form PestanasPrincipal
     */
    public PestanasPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        barraPrimaria = new javax.swing.JPanel();
        barraPrincipal = new javax.swing.JPanel();
        textoPestana = new javax.swing.JLabel();
        infoPestana = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        btnConsultas = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        creacionProyecto = new javax.swing.JPanel();
        informacionPerspectiva = new javax.swing.JPanel();
        informacionPerspectiva1c = new javax.swing.JPanel();
        btnAgregarPerspectiva = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        informacionPerspectiva1b = new javax.swing.JPanel();
        btnActivityRender = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        informacionPerspectiva1a = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFaceRecoder = new javax.swing.JLabel();
        ObtencionMuestras = new javax.swing.JPanel();
        btnObtencionMuestras = new javax.swing.JLabel();
        visualizacionMuestras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraPrimaria.setBackground(new java.awt.Color(56, 142, 60));

        javax.swing.GroupLayout barraPrimariaLayout = new javax.swing.GroupLayout(barraPrimaria);
        barraPrimaria.setLayout(barraPrimariaLayout);
        barraPrimariaLayout.setHorizontalGroup(
            barraPrimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2640, Short.MAX_VALUE)
        );
        barraPrimariaLayout.setVerticalGroup(
            barraPrimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        principal.add(barraPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2640, 20));

        barraPrincipal.setBackground(new java.awt.Color(76, 175, 80));

        textoPestana.setBackground(new java.awt.Color(76, 175, 80));
        textoPestana.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        textoPestana.setForeground(new java.awt.Color(255, 255, 255));
        textoPestana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoPestana.setText("Creación del proyecto");
        textoPestana.setOpaque(true);
        textoPestana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoPestanaMouseClicked(evt);
            }
        });

        infoPestana.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        infoPestana.setForeground(new java.awt.Color(200, 230, 201));
        infoPestana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoPestana.setText("Ingrese la información de su investigación");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Back-50.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Help.png"))); // NOI18N

        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Settings.png"))); // NOI18N

        javax.swing.GroupLayout barraPrincipalLayout = new javax.swing.GroupLayout(barraPrincipal);
        barraPrincipal.setLayout(barraPrincipalLayout);
        barraPrincipalLayout.setHorizontalGroup(
            barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAtras)
                .addGap(18, 18, 18)
                .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addComponent(textoPestana, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(451, 451, 451)
                        .addComponent(btnConsultas)
                        .addGap(65, 65, 65)
                        .addComponent(btnConfiguracion))
                    .addComponent(infoPestana, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1332, Short.MAX_VALUE))
        );
        barraPrincipalLayout.setVerticalGroup(
            barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrincipalLayout.createSequentialGroup()
                .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(textoPestana, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPestana))
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConsultas)
                            .addComponent(btnAtras)
                            .addComponent(btnConfiguracion))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        principal.add(barraPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 2640, 110));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setLayout(new java.awt.CardLayout());

        creacionProyecto.setBackground(new java.awt.Color(255, 255, 255));

        informacionPerspectiva.setBackground(new java.awt.Color(255, 255, 255));
        informacionPerspectiva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)));

        informacionPerspectiva1c.setBackground(new java.awt.Color(255, 255, 255));

        btnAgregarPerspectiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Add-50.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 33, 33));
        jLabel10.setText("Agregar Perspectiva");

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(117, 117, 117));
        jLabel9.setText("Agregue otra perspectiva ");

        informacionPerspectiva1b.setBackground(new java.awt.Color(255, 255, 255));
        informacionPerspectiva1b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        informacionPerspectiva1b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1bMouseExited(evt);
            }
        });

        btnActivityRender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Camera.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 33, 33));
        jLabel7.setText("Activity Render");

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(117, 117, 117));
        jLabel8.setText("Detección del individuo desde otra perspectiva");

        javax.swing.GroupLayout informacionPerspectiva1bLayout = new javax.swing.GroupLayout(informacionPerspectiva1b);
        informacionPerspectiva1b.setLayout(informacionPerspectiva1bLayout);
        informacionPerspectiva1bLayout.setHorizontalGroup(
            informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1bLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActivityRender)
                .addGap(18, 18, 18)
                .addGroup(informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        informacionPerspectiva1bLayout.setVerticalGroup(
            informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1bLayout.createSequentialGroup()
                .addGroup(informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacionPerspectiva1bLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActivityRender))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        informacionPerspectiva1a.setBackground(new java.awt.Color(255, 255, 255));
        informacionPerspectiva1a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1aMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 33, 33));
        jLabel5.setText("Face recoder");

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(117, 117, 117));
        jLabel6.setText("Detección frontal del individuo");

        btnFaceRecoder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-User Male_2.png"))); // NOI18N
        btnFaceRecoder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFaceRecoderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFaceRecoderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFaceRecoderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout informacionPerspectiva1aLayout = new javax.swing.GroupLayout(informacionPerspectiva1a);
        informacionPerspectiva1a.setLayout(informacionPerspectiva1aLayout);
        informacionPerspectiva1aLayout.setHorizontalGroup(
            informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacionPerspectiva1aLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFaceRecoder)
                .addGap(18, 18, 18)
                .addGroup(informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informacionPerspectiva1aLayout.setVerticalGroup(
            informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1aLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informacionPerspectiva1aLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(btnFaceRecoder))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout informacionPerspectiva1cLayout = new javax.swing.GroupLayout(informacionPerspectiva1c);
        informacionPerspectiva1c.setLayout(informacionPerspectiva1cLayout);
        informacionPerspectiva1cLayout.setHorizontalGroup(
            informacionPerspectiva1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionPerspectiva1b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(informacionPerspectiva1a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(informacionPerspectiva1cLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacionPerspectiva1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informacionPerspectiva1cLayout.setVerticalGroup(
            informacionPerspectiva1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1cLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(informacionPerspectiva1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informacionPerspectiva1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacionPerspectiva1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informacionPerspectiva1cLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(btnAgregarPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(391, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout informacionPerspectivaLayout = new javax.swing.GroupLayout(informacionPerspectiva);
        informacionPerspectiva.setLayout(informacionPerspectivaLayout);
        informacionPerspectivaLayout.setHorizontalGroup(
            informacionPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacionPerspectivaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informacionPerspectiva1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        informacionPerspectivaLayout.setVerticalGroup(
            informacionPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectivaLayout.createSequentialGroup()
                .addComponent(informacionPerspectiva1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout creacionProyectoLayout = new javax.swing.GroupLayout(creacionProyecto);
        creacionProyecto.setLayout(creacionProyectoLayout);
        creacionProyectoLayout.setHorizontalGroup(
            creacionProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creacionProyectoLayout.createSequentialGroup()
                .addComponent(informacionPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2249, Short.MAX_VALUE))
        );
        creacionProyectoLayout.setVerticalGroup(
            creacionProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionPerspectiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        contenido.add(creacionProyecto, "card2");

        ObtencionMuestras.setBackground(new java.awt.Color(255, 255, 255));

        btnObtencionMuestras.setText("Obtención de muestras");
        btnObtencionMuestras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObtencionMuestrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ObtencionMuestrasLayout = new javax.swing.GroupLayout(ObtencionMuestras);
        ObtencionMuestras.setLayout(ObtencionMuestrasLayout);
        ObtencionMuestrasLayout.setHorizontalGroup(
            ObtencionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObtencionMuestrasLayout.createSequentialGroup()
                .addGap(1116, 1116, 1116)
                .addComponent(btnObtencionMuestras)
                .addContainerGap(1413, Short.MAX_VALUE))
        );
        ObtencionMuestrasLayout.setVerticalGroup(
            ObtencionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObtencionMuestrasLayout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(btnObtencionMuestras)
                .addGap(146, 146, 146))
        );

        contenido.add(ObtencionMuestras, "card3");

        visualizacionMuestras.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Visualización de muestras");

        javax.swing.GroupLayout visualizacionMuestrasLayout = new javax.swing.GroupLayout(visualizacionMuestras);
        visualizacionMuestras.setLayout(visualizacionMuestrasLayout);
        visualizacionMuestrasLayout.setHorizontalGroup(
            visualizacionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizacionMuestrasLayout.createSequentialGroup()
                .addGap(1203, 1203, 1203)
                .addComponent(jLabel3)
                .addContainerGap(1316, Short.MAX_VALUE))
        );
        visualizacionMuestrasLayout.setVerticalGroup(
            visualizacionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visualizacionMuestrasLayout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
        );

        contenido.add(visualizacionMuestras, "card4");

        principal.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 2640, 510));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        principal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 1387, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoPestanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoPestanaMouseClicked
        // TODO add your handling code here:
     
      
        
    }//GEN-LAST:event_textoPestanaMouseClicked

    private void btnObtencionMuestrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObtencionMuestrasMouseClicked
        // TODO add your handling code here:
        textoPestana.setText("Visualización de muestras");
        infoPestana.setText("Gestione las muestras de su experimento");
        
        creacionProyecto.setVisible(false);
        ObtencionMuestras.setVisible(false);
        visualizacionMuestras.setVisible(true);
    }//GEN-LAST:event_btnObtencionMuestrasMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        // TODO add your handling code here:
         VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnFaceRecoderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaceRecoderMouseEntered
        // TODO add your handling code here:
        if (faceRecoder==true){
        
         btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else {
        btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Plus.png"))));
        }
       
        
    }//GEN-LAST:event_btnFaceRecoderMouseEntered

    private void btnFaceRecoderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaceRecoderMouseExited
        // TODO add your handling code here:
         btnFaceRecoder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-User Male_2.png")));
    }//GEN-LAST:event_btnFaceRecoderMouseExited

    private void btnFaceRecoderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaceRecoderMouseClicked
        // TODO add your handling code here:
      
                    
        
    }//GEN-LAST:event_btnFaceRecoderMouseClicked

    private void informacionPerspectiva1aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1aMouseEntered
        // TODO add your handling code here:
        if (faceRecoder==true){
        
         btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else {
        btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Plus.png"))));
               setLblColor(informacionPerspectiva1a);
        }
 
    }//GEN-LAST:event_informacionPerspectiva1aMouseEntered

    private void informacionPerspectiva1aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1aMouseExited
        // TODO add your handling code here:
                btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-User Male_2.png"))));
              if (faceRecoder==false){
        
       resetLblColor(informacionPerspectiva1a);
        }
        
    }//GEN-LAST:event_informacionPerspectiva1aMouseExited

    private void informacionPerspectiva1aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1aMouseClicked
        // TODO add your handling code here:
        if (faceRecoder == false){
        faceRecoder = true;
         setLblColor(informacionPerspectiva1a);
             btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else{
        faceRecoder = false;
         resetLblColor(informacionPerspectiva1a);
        }
    }//GEN-LAST:event_informacionPerspectiva1aMouseClicked

    private void informacionPerspectiva1bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1bMouseEntered
        // TODO add your handling code here:
            if (activityRender==true){
        
         btnActivityRender.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else {
        btnActivityRender.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Plus.png"))));
               setLblColor(informacionPerspectiva1b);
        }
        
    }//GEN-LAST:event_informacionPerspectiva1bMouseEntered

    private void informacionPerspectiva1bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1bMouseExited
        // TODO add your handling code here:
           btnActivityRender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Camera.png")));
              if (activityRender==false){
        
       resetLblColor(informacionPerspectiva1b);
        }
    }//GEN-LAST:event_informacionPerspectiva1bMouseExited

    private void informacionPerspectiva1bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1bMouseClicked
        // TODO add your handling code here:
         if (activityRender == false){
        activityRender = true;
         setLblColor(informacionPerspectiva1b);
             btnActivityRender.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else{
        activityRender = false;
         resetLblColor(informacionPerspectiva1b);
        }
    }//GEN-LAST:event_informacionPerspectiva1bMouseClicked
    
    public void setLblColor(JPanel lbl)
    {
        lbl.setBackground(new Color(200,230,201));
    }
    
      public void resetLblColor(JPanel lbl)
    {
        lbl.setBackground(new Color(255,255,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PestanasPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ObtencionMuestras;
    private javax.swing.JPanel barraPrimaria;
    private javax.swing.JPanel barraPrincipal;
    private javax.swing.JLabel btnActivityRender;
    private javax.swing.JLabel btnAgregarPerspectiva;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnConfiguracion;
    private javax.swing.JLabel btnConsultas;
    private javax.swing.JLabel btnFaceRecoder;
    private javax.swing.JLabel btnObtencionMuestras;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel creacionProyecto;
    private javax.swing.JLabel infoPestana;
    private javax.swing.JPanel informacionPerspectiva;
    private javax.swing.JPanel informacionPerspectiva1a;
    private javax.swing.JPanel informacionPerspectiva1b;
    private javax.swing.JPanel informacionPerspectiva1c;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel principal;
    private javax.swing.JLabel textoPestana;
    private javax.swing.JPanel visualizacionMuestras;
    // End of variables declaration//GEN-END:variables
}
