/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeebox.vistas;
import infoProyecto.CapturaInformacion;
import perspectiva.PerspectivaCliente;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Katherine
 */
public class PestanasPrincipal extends javax.swing.JFrame {
    
    CapturaInformacion informacionProyecto = new CapturaInformacion();
    boolean faceRecoder = false;
    boolean activityRender = false;
    boolean nuevaPerspectiva = false;
    String direccionIpEscrita,dispositivoSeleccionado;
    ArrayList<String> dipositivos ;
    boolean ipValida= true;
    public static boolean ScreenGo = false;
    public static boolean ScreenStop = false;
    public boolean abortar = false;
    
    //Socket 
    private final String ipOld = "";
    private PerspectivaCliente pc = null;
    

    /**
     * Creates new form PestanasPrincipal
     */
    public PestanasPrincipal() {
        initComponents();
        conexion.setVisible(false);
        txtSeleccionarDispositivo.setVisible(false);
        btnSeleccionarDispositivo.setVisible(false);
        txtDispositivoSeleccionado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        barraPrimaria = new javax.swing.JPanel();
        barraPrincipal = new javax.swing.JPanel();
        textoPestana = new javax.swing.JLabel();
        infoPestana = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        btnConsultas = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        creacionProyecto = new javax.swing.JPanel();
        informacionPerspectiva = new javax.swing.JPanel();
        informacionPerspectiva1c = new javax.swing.JPanel();
        informacionPerspectiva1b = new javax.swing.JPanel();
        btnActivityRender = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        informacionPerspectiva1a = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFaceRecoder = new javax.swing.JLabel();
        agregarPerspectiva = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarPerspectiva = new javax.swing.JLabel();
        conexion = new javax.swing.JPanel();
        btnBuscarDireccionIp = new javax.swing.JLabel();
        direccionIp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSeleccionarDispositivo = new javax.swing.JLabel();
        btnSeleccionarDispositivo = new javax.swing.JLabel();
        txtDispositivoSeleccionado = new javax.swing.JLabel();
        informacionDelProyecto = new javax.swing.JPanel();
        ObtencionMuestras = new javax.swing.JPanel();
        btnObtencionMuestras = new javax.swing.JLabel();
        visualizacionMuestras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraPrimaria.setBackground(new java.awt.Color(56, 142, 60));

        javax.swing.GroupLayout barraPrimariaLayout = new javax.swing.GroupLayout(barraPrimaria);
        barraPrimaria.setLayout(barraPrimariaLayout);
        barraPrimariaLayout.setHorizontalGroup(
            barraPrimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2640, Short.MAX_VALUE)
        );
        barraPrimariaLayout.setVerticalGroup(
            barraPrimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        principal.add(barraPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2640, 20));

        barraPrincipal.setBackground(new java.awt.Color(76, 175, 80));

        textoPestana.setBackground(new java.awt.Color(76, 175, 80));
        textoPestana.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        textoPestana.setForeground(new java.awt.Color(255, 255, 255));
        textoPestana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoPestana.setText("Creación del proyecto");
        textoPestana.setOpaque(true);
        textoPestana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoPestanaMouseClicked(evt);
            }
        });

        infoPestana.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        infoPestana.setForeground(new java.awt.Color(200, 230, 201));
        infoPestana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoPestana.setText("Ingrese la información de su investigación");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Back-50.png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Help.png"))); // NOI18N

        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Settings.png"))); // NOI18N

        javax.swing.GroupLayout barraPrincipalLayout = new javax.swing.GroupLayout(barraPrincipal);
        barraPrincipal.setLayout(barraPrincipalLayout);
        barraPrincipalLayout.setHorizontalGroup(
            barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAtras)
                .addGap(18, 18, 18)
                .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addComponent(textoPestana, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(451, 451, 451)
                        .addComponent(btnConsultas)
                        .addGap(65, 65, 65)
                        .addComponent(btnConfiguracion))
                    .addComponent(infoPestana, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1332, Short.MAX_VALUE))
        );
        barraPrincipalLayout.setVerticalGroup(
            barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrincipalLayout.createSequentialGroup()
                .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(textoPestana, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPestana))
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConsultas)
                            .addComponent(btnAtras)
                            .addComponent(btnConfiguracion))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        principal.add(barraPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 2640, 110));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setLayout(new java.awt.CardLayout());

        creacionProyecto.setBackground(new java.awt.Color(255, 255, 255));
        creacionProyecto.setForeground(new java.awt.Color(33, 33, 33));
        creacionProyecto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        informacionPerspectiva.setBackground(new java.awt.Color(255, 255, 255));

        informacionPerspectiva1c.setBackground(new java.awt.Color(255, 255, 255));
        informacionPerspectiva1c.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)));

        informacionPerspectiva1b.setBackground(new java.awt.Color(255, 255, 255));
        informacionPerspectiva1b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        informacionPerspectiva1b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1bMouseExited(evt);
            }
        });

        btnActivityRender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Camera.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 33, 33));
        jLabel7.setText("Activity Render");

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(117, 117, 117));
        jLabel8.setText("Detección del individuo desde otra perspectiva");

        javax.swing.GroupLayout informacionPerspectiva1bLayout = new javax.swing.GroupLayout(informacionPerspectiva1b);
        informacionPerspectiva1b.setLayout(informacionPerspectiva1bLayout);
        informacionPerspectiva1bLayout.setHorizontalGroup(
            informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1bLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActivityRender)
                .addGap(18, 18, 18)
                .addGroup(informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informacionPerspectiva1bLayout.setVerticalGroup(
            informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1bLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionPerspectiva1bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActivityRender)
                    .addGroup(informacionPerspectiva1bLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        informacionPerspectiva1a.setBackground(new java.awt.Color(255, 255, 255));
        informacionPerspectiva1a.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        informacionPerspectiva1a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informacionPerspectiva1aMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 33, 33));
        jLabel5.setText("Face recoder");

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(117, 117, 117));
        jLabel6.setText("Detección frontal del individuo");

        btnFaceRecoder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-User Male_2.png"))); // NOI18N
        btnFaceRecoder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFaceRecoderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFaceRecoderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFaceRecoderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout informacionPerspectiva1aLayout = new javax.swing.GroupLayout(informacionPerspectiva1a);
        informacionPerspectiva1a.setLayout(informacionPerspectiva1aLayout);
        informacionPerspectiva1aLayout.setHorizontalGroup(
            informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacionPerspectiva1aLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFaceRecoder)
                .addGap(18, 18, 18)
                .addGroup(informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informacionPerspectiva1aLayout.setVerticalGroup(
            informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1aLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionPerspectiva1aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informacionPerspectiva1aLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(btnFaceRecoder))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        agregarPerspectiva.setBackground(new java.awt.Color(255, 255, 255));
        agregarPerspectiva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarPerspectiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarPerspectivaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarPerspectivaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarPerspectivaMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(117, 117, 117));
        jLabel13.setText("Agregue otra perspectiva ");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 33, 33));
        jLabel10.setText("Agregar Perspectiva");

        btnAgregarPerspectiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Add-50.png"))); // NOI18N
        btnAgregarPerspectiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPerspectivaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout agregarPerspectivaLayout = new javax.swing.GroupLayout(agregarPerspectiva);
        agregarPerspectiva.setLayout(agregarPerspectivaLayout);
        agregarPerspectivaLayout.setHorizontalGroup(
            agregarPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPerspectivaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregarPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregarPerspectivaLayout.setVerticalGroup(
            agregarPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPerspectivaLayout.createSequentialGroup()
                .addGroup(agregarPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(agregarPerspectivaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(agregarPerspectivaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout informacionPerspectiva1cLayout = new javax.swing.GroupLayout(informacionPerspectiva1c);
        informacionPerspectiva1c.setLayout(informacionPerspectiva1cLayout);
        informacionPerspectiva1cLayout.setHorizontalGroup(
            informacionPerspectiva1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionPerspectiva1b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(informacionPerspectiva1a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(agregarPerspectiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        informacionPerspectiva1cLayout.setVerticalGroup(
            informacionPerspectiva1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectiva1cLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(informacionPerspectiva1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informacionPerspectiva1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conexion.setBackground(new java.awt.Color(255, 255, 255));
        conexion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)));

        btnBuscarDireccionIp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Search.png"))); // NOI18N
        btnBuscarDireccionIp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarDireccionIpMouseClicked(evt);
            }
        });

        direccionIp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        direccionIp.setForeground(new java.awt.Color(117, 117, 117));
        direccionIp.setBorder(null);
        direccionIp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionIpFocusGained(evt);
            }
        });
        direccionIp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionIpMouseClicked(evt);
            }
        });
        direccionIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionIpActionPerformed(evt);
            }
        });
        direccionIp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionIpKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 33, 33));
        jLabel11.setText("Ingrese dirección IP");

        txtSeleccionarDispositivo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSeleccionarDispositivo.setForeground(new java.awt.Color(33, 33, 33));
        txtSeleccionarDispositivo.setText("Seleccionar Dispositivo");

        btnSeleccionarDispositivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-More Than.png"))); // NOI18N
        btnSeleccionarDispositivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarDispositivoMouseClicked(evt);
            }
        });

        txtDispositivoSeleccionado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDispositivoSeleccionado.setForeground(new java.awt.Color(117, 117, 117));
        txtDispositivoSeleccionado.setText("Dispositivo seleccionado");

        javax.swing.GroupLayout conexionLayout = new javax.swing.GroupLayout(conexion);
        conexion.setLayout(conexionLayout);
        conexionLayout.setHorizontalGroup(
            conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(conexionLayout.createSequentialGroup()
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionIp, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarDireccionIp))
                    .addGroup(conexionLayout.createSequentialGroup()
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeleccionarDispositivo)
                            .addComponent(txtDispositivoSeleccionado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarDispositivo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        conexionLayout.setVerticalGroup(
            conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexionLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionIp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarDireccionIp, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conexionLayout.createSequentialGroup()
                        .addComponent(txtSeleccionarDispositivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDispositivoSeleccionado))
                    .addComponent(btnSeleccionarDispositivo))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout informacionPerspectivaLayout = new javax.swing.GroupLayout(informacionPerspectiva);
        informacionPerspectiva.setLayout(informacionPerspectivaLayout);
        informacionPerspectivaLayout.setHorizontalGroup(
            informacionPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacionPerspectivaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conexion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(informacionPerspectivaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(informacionPerspectiva1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );
        informacionPerspectivaLayout.setVerticalGroup(
            informacionPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPerspectivaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacionPerspectiva1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        informacionDelProyecto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout informacionDelProyectoLayout = new javax.swing.GroupLayout(informacionDelProyecto);
        informacionDelProyecto.setLayout(informacionDelProyectoLayout);
        informacionDelProyectoLayout.setHorizontalGroup(
            informacionDelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        informacionDelProyectoLayout.setVerticalGroup(
            informacionDelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout creacionProyectoLayout = new javax.swing.GroupLayout(creacionProyecto);
        creacionProyecto.setLayout(creacionProyectoLayout);
        creacionProyectoLayout.setHorizontalGroup(
            creacionProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creacionProyectoLayout.createSequentialGroup()
                .addComponent(informacionPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1944, Short.MAX_VALUE))
        );
        creacionProyectoLayout.setVerticalGroup(
            creacionProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionPerspectiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(creacionProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacionDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenido.add(creacionProyecto, "card2");

        ObtencionMuestras.setBackground(new java.awt.Color(255, 255, 255));

        btnObtencionMuestras.setText("Obtención de muestras");
        btnObtencionMuestras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObtencionMuestrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ObtencionMuestrasLayout = new javax.swing.GroupLayout(ObtencionMuestras);
        ObtencionMuestras.setLayout(ObtencionMuestrasLayout);
        ObtencionMuestrasLayout.setHorizontalGroup(
            ObtencionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObtencionMuestrasLayout.createSequentialGroup()
                .addGap(1116, 1116, 1116)
                .addComponent(btnObtencionMuestras)
                .addContainerGap(1413, Short.MAX_VALUE))
        );
        ObtencionMuestrasLayout.setVerticalGroup(
            ObtencionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObtencionMuestrasLayout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(btnObtencionMuestras)
                .addGap(146, 146, 146))
        );

        contenido.add(ObtencionMuestras, "card3");

        visualizacionMuestras.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Visualización de muestras");

        javax.swing.GroupLayout visualizacionMuestrasLayout = new javax.swing.GroupLayout(visualizacionMuestras);
        visualizacionMuestras.setLayout(visualizacionMuestrasLayout);
        visualizacionMuestrasLayout.setHorizontalGroup(
            visualizacionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizacionMuestrasLayout.createSequentialGroup()
                .addGap(1203, 1203, 1203)
                .addComponent(jLabel3)
                .addContainerGap(1316, Short.MAX_VALUE))
        );
        visualizacionMuestrasLayout.setVerticalGroup(
            visualizacionMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visualizacionMuestrasLayout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
        );

        contenido.add(visualizacionMuestras, "card4");

        principal.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 2640, 510));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        principal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 1387, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoPestanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoPestanaMouseClicked
        // TODO add your handling code here:
     
      
        
    }//GEN-LAST:event_textoPestanaMouseClicked

    private void btnObtencionMuestrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObtencionMuestrasMouseClicked
        // TODO add your handling code here:
        textoPestana.setText("Visualización de muestras");
        infoPestana.setText("Gestione las muestras de su experimento");
        
        creacionProyecto.setVisible(false);
        ObtencionMuestras.setVisible(false);
        visualizacionMuestras.setVisible(true);
    }//GEN-LAST:event_btnObtencionMuestrasMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        // TODO add your handling code here:
         VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnFaceRecoderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaceRecoderMouseEntered
        // TODO add your handling code here:
        if (faceRecoder==true){
        
         btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else {
        btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Plus.png"))));
        }
       
        
    }//GEN-LAST:event_btnFaceRecoderMouseEntered

    private void btnFaceRecoderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaceRecoderMouseExited
        // TODO add your handling code here:
         btnFaceRecoder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-User Male_2.png")));
    }//GEN-LAST:event_btnFaceRecoderMouseExited

    private void btnFaceRecoderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaceRecoderMouseClicked
        // TODO add your handling code here:
      
                    
        
    }//GEN-LAST:event_btnFaceRecoderMouseClicked

    private void informacionPerspectiva1aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1aMouseEntered
        // TODO add your handling code here:
        if (faceRecoder==true){
        
         btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else {
        btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Plus.png"))));
               setLblColor(informacionPerspectiva1a);
        }
 
    }//GEN-LAST:event_informacionPerspectiva1aMouseEntered

    private void informacionPerspectiva1aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1aMouseExited
        // TODO add your handling code here:
                btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-User Male_2.png"))));
              if (faceRecoder==false){
        
       resetLblColor(informacionPerspectiva1a);
        }
        
    }//GEN-LAST:event_informacionPerspectiva1aMouseExited

    private void informacionPerspectiva1aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1aMouseClicked
        // TODO add your handling code here:
        if (faceRecoder == false){
        faceRecoder = true;
         setLblColor(informacionPerspectiva1a);
             btnFaceRecoder.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else{
        faceRecoder = false;
         resetLblColor(informacionPerspectiva1a);
        }
    }//GEN-LAST:event_informacionPerspectiva1aMouseClicked

    private void informacionPerspectiva1bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1bMouseEntered
        // TODO add your handling code here:
            if (activityRender==true){
        
         btnActivityRender.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else {
        btnActivityRender.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Plus.png"))));
               setLblColor(informacionPerspectiva1b);
        }
        
    }//GEN-LAST:event_informacionPerspectiva1bMouseEntered

    private void informacionPerspectiva1bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1bMouseExited
        // TODO add your handling code here:
           btnActivityRender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Camera.png")));
              if (activityRender==false){
        
       resetLblColor(informacionPerspectiva1b);
        }
    }//GEN-LAST:event_informacionPerspectiva1bMouseExited

    private void informacionPerspectiva1bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionPerspectiva1bMouseClicked
        // TODO add your handling code here:
         if (activityRender == false){
        activityRender = true;
         setLblColor(informacionPerspectiva1b);
             btnActivityRender.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else{
        activityRender = false;
         resetLblColor(informacionPerspectiva1b);
        }
    }//GEN-LAST:event_informacionPerspectiva1bMouseClicked

    private void direccionIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionIpActionPerformed

    private void direccionIpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionIpFocusGained
        // TODO add your handling code here:
        //direccionIp.setText("");
       
    }//GEN-LAST:event_direccionIpFocusGained

    private void direccionIpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionIpMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_direccionIpMouseClicked

    private void direccionIpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionIpKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_direccionIpKeyTyped

    private void btnBuscarDireccionIpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDireccionIpMouseClicked
        // TODO add your handling code here:
        System.out.println("");
         direccionIpEscrita=direccionIp.getText();
         if(!"".equals(direccionIpEscrita) && !ipOld.equals(direccionIpEscrita)){
             
             ipValida= true;
             /**/
           new Thread(new Runnable (){
           @Override
           public void run(){
               pc = new PerspectivaCliente(direccionIpEscrita);
               if(PerspectivaCliente.con){
               pc.start();
               pc.enviarInstruccion("DISPOSITIVOS");
               System.out.println("Enviando instruccion a servidor: DISPOSITIVOS");
               while(!PerspectivaCliente.listaDispositivos){
                   System.out.println("Esperando dispositivos");
               }
               
               List<String> dispositivos = pc.getDispositivos();
               String[] dis = new String[dispositivos.size()];
                        for (int i = 0; i < dispositivos.size(); i++) {
                            dis[i] = dispositivos.get(i);
                            System.out.println(dispositivos.get(i));
                        }
              txtSeleccionarDispositivo.setVisible(true);
             btnSeleccionarDispositivo.setVisible(true);
             txtDispositivoSeleccionado.setVisible(true);
               
               
               } else {
                   System.out.println("\"No se puede conectar con IP ingresada\"");
               }
               
               
               
           }
           
           }).start();
             
         }
         else if ("".equals(direccionIpEscrita))
         {
             //pop up que indique que la ip no es valida
             System.out.println("\"Debe ingresar IP\"");
         }
         else if(ipOld.equals(direccionIpEscrita)){
             System.out.println( "Ingresó la misma IP");
         }
        
    }//GEN-LAST:event_btnBuscarDireccionIpMouseClicked

    private void btnAgregarPerspectivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPerspectivaMouseClicked
        // TODO add your handling code here:
        conexion.setVisible(true);
    }//GEN-LAST:event_btnAgregarPerspectivaMouseClicked

    private void agregarPerspectivaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarPerspectivaMouseEntered
        // TODO add your handling code here:
          if (nuevaPerspectiva==true){
        
         btnAgregarPerspectiva.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
        }
        else {
        btnAgregarPerspectiva.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Plus.png"))));
               setLblColor(agregarPerspectiva);
        }
    }//GEN-LAST:event_agregarPerspectivaMouseEntered

    private void agregarPerspectivaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarPerspectivaMouseExited
        // TODO add your handling code here:
       btnAgregarPerspectiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Add-50.png")));
              if (nuevaPerspectiva==false){
        
       resetLblColor(agregarPerspectiva);
        }
    }//GEN-LAST:event_agregarPerspectivaMouseExited

    private void agregarPerspectivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarPerspectivaMouseClicked
        // TODO add your handling code here:
          if (nuevaPerspectiva == false){
        nuevaPerspectiva = true;
         setLblColor(agregarPerspectiva);
          //
             btnAgregarPerspectiva.setIcon((new javax.swing.ImageIcon(getClass().getResource("/icon/delete_black.png"))));
             conexion.setVisible(true);
        }
        else{
        nuevaPerspectiva = false;
         resetLblColor(agregarPerspectiva);
          conexion.setVisible(false);
        }
    }//GEN-LAST:event_agregarPerspectivaMouseClicked

    private void btnSeleccionarDispositivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarDispositivoMouseClicked
        // TODO add your handling code here:
        PopUpSeleccionarDispositivo popUpSeleccionarDispositivo = new PopUpSeleccionarDispositivo();
        popUpSeleccionarDispositivo.setVisible(true);
        
       
        
    }//GEN-LAST:event_btnSeleccionarDispositivoMouseClicked
    public void activarDispositivoSeleccionado(){
     if (informacionProyecto.getDispositivoSeleccionado()==true){
         
         
         
        }
    }
    
    public void setLblColor(JPanel lbl)
    {
        lbl.setBackground(new Color(200,230,201));
    }
    
      public void resetLblColor(JPanel lbl)
    {
        lbl.setBackground(new Color(255,255,255));
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PestanasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PestanasPrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ObtencionMuestras;
    private javax.swing.JPanel agregarPerspectiva;
    private javax.swing.JPanel barraPrimaria;
    private javax.swing.JPanel barraPrincipal;
    private javax.swing.JLabel btnActivityRender;
    private javax.swing.JLabel btnAgregarPerspectiva;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnBuscarDireccionIp;
    private javax.swing.JLabel btnConfiguracion;
    private javax.swing.JLabel btnConsultas;
    private javax.swing.JLabel btnFaceRecoder;
    private javax.swing.JLabel btnObtencionMuestras;
    private javax.swing.JLabel btnSeleccionarDispositivo;
    private javax.swing.JPanel conexion;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel creacionProyecto;
    private javax.swing.JTextField direccionIp;
    private javax.swing.JLabel infoPestana;
    private javax.swing.JPanel informacionDelProyecto;
    private javax.swing.JPanel informacionPerspectiva;
    private javax.swing.JPanel informacionPerspectiva1a;
    private javax.swing.JPanel informacionPerspectiva1b;
    private javax.swing.JPanel informacionPerspectiva1c;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel principal;
    private javax.swing.JLabel textoPestana;
    private javax.swing.JLabel txtDispositivoSeleccionado;
    private javax.swing.JLabel txtSeleccionarDispositivo;
    private javax.swing.JPanel visualizacionMuestras;
    // End of variables declaration//GEN-END:variables
}
