/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeebox.vistas;

import java.io.File;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Katherine
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        barraPrimaria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraPrincipal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        iconAyuda = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nuevoProyecto = new javax.swing.JPanel();
        iconNuevoProyecto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        abrirProyecto = new javax.swing.JPanel();
        iconAbrirProyecto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRutaProyecto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraPrimaria.setBackground(new java.awt.Color(56, 142, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("eBox");

        javax.swing.GroupLayout barraPrimariaLayout = new javax.swing.GroupLayout(barraPrimaria);
        barraPrimaria.setLayout(barraPrimariaLayout);
        barraPrimariaLayout.setHorizontalGroup(
            barraPrimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrimariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1318, Short.MAX_VALUE))
        );
        barraPrimariaLayout.setVerticalGroup(
            barraPrimariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraPrimariaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel3.add(barraPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 50));

        barraPrincipal.setBackground(new java.awt.Color(76, 175, 80));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Archivo");

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(200, 230, 201));
        jLabel7.setText("Seleccione la opción que desea realizar");

        iconAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Help.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Settings.png"))); // NOI18N

        javax.swing.GroupLayout barraPrincipalLayout = new javax.swing.GroupLayout(barraPrincipal);
        barraPrincipal.setLayout(barraPrincipalLayout);
        barraPrincipalLayout.setHorizontalGroup(
            barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrincipalLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(barraPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 936, Short.MAX_VALUE)
                        .addComponent(iconAyuda)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel8)
                        .addGap(75, 75, 75))))
        );
        barraPrincipalLayout.setVerticalGroup(
            barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPrincipalLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(barraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.add(barraPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 210));

        nuevoProyecto.setBackground(new java.awt.Color(255, 255, 255));
        nuevoProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevoProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoProyectoMouseExited(evt);
            }
        });

        iconNuevoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Add Folder.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(33, 33, 33));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Nuevo Proyecto");

        jLabel3.setBackground(new java.awt.Color(117, 117, 117));
        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(117, 117, 117));
        jLabel3.setText("Cree un nuevo proyecto para su experimento");

        javax.swing.GroupLayout nuevoProyectoLayout = new javax.swing.GroupLayout(nuevoProyecto);
        nuevoProyecto.setLayout(nuevoProyectoLayout);
        nuevoProyectoLayout.setHorizontalGroup(
            nuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoProyectoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(iconNuevoProyecto)
                .addGap(34, 34, 34)
                .addGroup(nuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(852, Short.MAX_VALUE))
        );
        nuevoProyectoLayout.setVerticalGroup(
            nuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoProyectoLayout.createSequentialGroup()
                .addGroup(nuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoProyectoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(iconNuevoProyecto))
                    .addGroup(nuevoProyectoLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel3.add(nuevoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1380, 210));

        abrirProyecto.setBackground(new java.awt.Color(255, 255, 255));
        abrirProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        abrirProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abrirProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abrirProyectoMouseExited(evt);
            }
        });

        iconAbrirProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Open.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(33, 33, 33));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setText("Archivo Seleccionado:");

        jLabel4.setBackground(new java.awt.Color(117, 117, 117));
        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(117, 117, 117));
        jLabel4.setText("Seleccione un proyecto previamente creado");

        jLabel9.setBackground(new java.awt.Color(33, 33, 33));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setText("Abrir Proyecto");

        txtRutaProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaProyectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abrirProyectoLayout = new javax.swing.GroupLayout(abrirProyecto);
        abrirProyecto.setLayout(abrirProyectoLayout);
        abrirProyectoLayout.setHorizontalGroup(
            abrirProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrirProyectoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(iconAbrirProyecto)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(129, 129, 129)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRutaProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(abrirProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(abrirProyectoLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(jLabel9)
                    .addContainerGap(1037, Short.MAX_VALUE)))
        );
        abrirProyectoLayout.setVerticalGroup(
            abrirProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrirProyectoLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(abrirProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abrirProyectoLayout.createSequentialGroup()
                        .addComponent(iconAbrirProyecto)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abrirProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abrirProyectoLayout.createSequentialGroup()
                        .addGroup(abrirProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRutaProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(95, 95, 95))))
            .addGroup(abrirProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abrirProyectoLayout.createSequentialGroup()
                    .addContainerGap(100, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(91, 91, 91)))
        );

        jPanel3.add(abrirProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1380, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProyectoMouseEntered
        // TODO add your handling code here:
        setColor(nuevoProyecto);
    }//GEN-LAST:event_nuevoProyectoMouseEntered

    private void nuevoProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProyectoMouseExited
        // TODO add your handling code here:
         resetColor(nuevoProyecto);
    }//GEN-LAST:event_nuevoProyectoMouseExited

    private void abrirProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirProyectoMouseEntered
        // TODO add your handling code here:
        setColor(abrirProyecto);
    }//GEN-LAST:event_abrirProyectoMouseEntered

    private void abrirProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirProyectoMouseExited
        // TODO add your handling code here:
        resetColor(abrirProyecto);
    }//GEN-LAST:event_abrirProyectoMouseExited

    private void nuevoProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProyectoMouseClicked
        // TODO add your handling code here:
  
        PestanasPrincipal pestanasPrincipal = new PestanasPrincipal();
        pestanasPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuevoProyectoMouseClicked

    private void abrirProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirProyectoMouseClicked
        // TODO add your handling code here:
           System.out.println("se hizo clic");
       
        seleccionarArchivo(JFileChooser.FILES_ONLY, "Abrir", txtRutaProyecto, "ebox", "C:\\");
        System.out.println("txt ruta Proyecto: "+ txtRutaProyecto.getText());
        
        
    }//GEN-LAST:event_abrirProyectoMouseClicked

    private void txtRutaProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaProyectoActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtRutaProyectoActionPerformed
     public void setColor(JPanel panel){
          panel.setBackground(new java.awt.Color(200,230,201));
     }   
     public void resetColor(JPanel panel){
          panel.setBackground(new java.awt.Color(255,255,255));
     } 
     private void seleccionarArchivo(int fileSelectionMode, String approveButtonText, JTextField field, String fileFilter, String currentDirectory){
         System.out.println("entre");
         JFileChooser fileChooser = new JFileChooser();
     fileChooser.setFileSelectionMode(fileSelectionMode);
     if(!"".equals(fileFilter)){
         FileNameExtensionFilter filtro = new FileNameExtensionFilter("*." + fileFilter, fileFilter.toLowerCase(), fileFilter.toUpperCase());
         fileChooser.setFileFilter(filtro);
     }
     fileChooser.setCurrentDirectory(new File(currentDirectory));
     int result = fileChooser.showDialog(this, approveButtonText);
      if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            field.setText(selectedFile.getAbsolutePath());
        }
     
     }
    /**
     * @param args the command line arguments
     */
    public void iniciar(){
    new VentanaPrincipal().setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abrirProyecto;
    private javax.swing.JPanel barraPrimaria;
    private javax.swing.JPanel barraPrincipal;
    private javax.swing.JLabel iconAbrirProyecto;
    private javax.swing.JLabel iconAyuda;
    private javax.swing.JLabel iconNuevoProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel nuevoProyecto;
    private javax.swing.JTextField txtRutaProyecto;
    // End of variables declaration//GEN-END:variables
}
